- name: Filters Demo
  hosts: servera*
  gather_facts: true
  tasks:

    - name: Facts from Server A
      ansible.builtin.debug:
        msg: "{{ ansible_facts.ansible_local.emp.user.userid }}"


    - name: Create Users
      ansible.builtin.user:
        name: "{{ ansible_facts.ansible_local.emp.user.username | lower }}"
        comment: "{{ ansible_facts.ansible_local.emp.user.username | upper }} ++++ {{ ansible_facts.ansible_local.emp.dept.location | upper }}"
        password: "{{ 'redhat123' | password_hash('sha512') }}"
      become: true
      delegate_to: serverb.lab.example.com
      delegate_facts: true
