- name: Template App of Web Server
  hosts: all
  # gather_facts: false
  become: true
  tasks:
    - name: Set Fact for Group Names
      ansible.builtin.set_fact:
        mygroups: "{{ group_names }}"

    - name: Deploy Web app
      ansible.builtin.template:
        src: j2/complex.j2
        dest: /tmp/index.html
        mode: 0644
      when: inventory_hostname in groups["control"]
